### ISSUE TITLE
Values not matching

### ISSUE THREAD

**Issue by TungyuYoung** [hangtingchen/Complexity-Scaling-for-Speech-Denoising.github.io#1]
Dear Chen,
I think that you might have made some mistakes in the Introduction and demos of "Complexity Scaling for Speech Denoising".

As shown in Table VI, the values of STOI and SI-SNR are not matching.

**Comment by hangtingchen** [comment]
Yeah, you are right. There is something misaligned in the table VI. I have just updated the website. Feel free to tell me if something is still wrong.
